name: Build and Push to GHCR

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # Needed to push to GHCR
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/sample-service:latest .
          docker tag ghcr.io/${{ github.repository_owner }}/sample-service:latest ghcr.io/${{ github.repository_owner }}/sample-service:${{ github.run_number }}

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/sample-service:latest
          docker push ghcr.io/${{ github.repository_owner }}/sample-service:${{ github.run_number }}
